graphite_url = 'http://graphitemachine'
anthracite_url = None
listen_host = '0.0.0.0'  # defaults to "all interfaces"
listen_port = 8080
filename_metrics = 'metrics.json'
log_file = 'graph-explorer.log'
mysql_user = "carbon_tagger"
mysql_passwd = "carbon_tagger_pw"
mysql_host = "graphite_machine
mysql_db= "carbon_tagger"
es_host = "es_host"
es_port = 9200
