graphite_url = 'http://graphitemachine'
graphite_username = None
graphite_password = None
anthracite_url = None
listen_host = '0.0.0.0'  # defaults to "all interfaces"
listen_port = 8080
filename_metrics = 'metrics.json'
log_file = 'graph-explorer.log'
es_host = "elasticsearch_host"
es_port = 9200
